{
  "status" : "fail",
  "tests" : [
    {
      "name" : "MultipleWithExceptionTests.testAdd",
      "status" : "pass"
    },
    {
      "name" : "MultipleWithExceptionTests.testSub",
      "status" : "pass"
    },
    {
      "name" : "MultipleWithExceptionTests.testMul",
      "status" : "pass"
    },
    {
      "message" : "/solution/Tests/MultipleWithExceptionTests/MultipleWithExceptionTests.swift:19: error: MultipleWithExceptionTests.testThrow : XCTAssertEqual threw error \"testError(\"Oh noes! Div by zeroes!!!\")\" - ",
      "name" : "MultipleWithExceptionTests.testThrow",
      "status" : "fail"
    }
  ]
}