{
    "status" : "fail",
    "tests" : [
      {
        "name" : "testAdd",
        "status" : "pass",
        "task_id" : 1,
        "test_code" : "XCTAssertEqual(sum(2, 3), 5, \"2+3 should equal 5\")"
      },
      {
        "name" : "testSub",
        "status" : "pass",
        "task_id" : 1,
        "test_code" : "XCTAssertEqual(sub(2, 3), -1)"
      },
      {
        "name" : "testMul",
        "status" : "pass",
        "task_id" : 1,
        "test_code" : "XCTAssertEqual(mul(3, 2), 6)"
      },
      {
        "message" : "Test Suite 'Selected tests' started at 2023-06-07 15:30:14.363Test Suite 'MultipleWithExceptionTests' started at 2023-06-07 15:30:14.364Test Case 'MultipleWithExceptionTests.testThrow' started at 2023-06-07 15:30:14.364/solution/Tests/MultipleWithExceptionTests/MultipleWithExceptionTests.swift:19: error: MultipleWithExceptionTests.testThrow : XCTAssertEqual threw error \"testError(\"Oh noes! Div by zeroes!!!\")\" -Test Case 'MultipleWithExceptionTests.testThrow' failed (0.101 seconds)Test Suite 'MultipleWithExceptionTests' failed at 2023-06-07 15:30:14.465",
        "name" : "testThrow",
        "status" : "error",
        "task_id" : 1,
        "test_code" : "XCTAssertEqual(try throwErr(2, 0), 6)"
      }
    ],
    "version" : 3
  }